# Generated by Django 5.0.3 on 2024-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='users'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
