version: "3.8"
x-service: &service
  build:
    dockerfile: ./docker/backend/Dockerfile
    context: ./
  env_file:
    - .env
  image: remembrancer/backend-${ENVIRONMENT}
services:
  api:
    <<: *service
    container_name: remembrancer-api-${ENVIRONMENT}
    command:
      - prod
    image: remembrancer/backend-${ENVIRONMENT}
  celery:
    <<: *service
    depends_on:
      - redis
    command: celery worker -l INFO -Q django
  nginx:
    container_name: remembrancer-nginx-${ENVIRONMENT}
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ./
      args:
        - API_URL
    ports:
      - "${SERVICE_PORT}:80"
    volumes:
      - static:/static
      - attachments:/attachments
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  redis:
    image: 'ghcr.io/microsoft/garnet'
    ulimits:
      memlock: -1
    volumes:
      - redis_data:/data
volumes:
  static:
  attachments:
  redis_data:
